### ISSUE TITLE
CDI Forms - references link

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#28]
References link from main page goes to an empty page - get rid of it.

Just have references link from each of the sub-pages (English long, English short, etc).

**Comment by esalling23** [comment]
it doesn't go to an empty page, it goes to the page with all of the the other references on it-- i can remove it but the page automatically opens as that link regardless, with the small amount of content there--

**Comment by vmarchman** [comment]
It seems like there are two links to the references.  One off of the very first forms page and then another one takes you to a completely different set of links with just English Long, English Short and Spanish Long.

**Comment by esalling23** [comment]
I've gone through and checked, there are a total of 4 References links (1) On the CDI Forms tab, (2) on the English Long Tab, (3) on the English Short Tab, and (4) on the Spanish Long Tab
Each links to "references.html" which is a page VERY similar to the "forms.html" page but only has the above 4 tabs because those were the only ones with references (CDI Forms tab is kept as a "home" tab)

**Comment by vmarchman** [comment]
Maybe we can talk about this one?
